### ISSUE TITLE
Error with numpy/Tensorflow during installation

### ISSUE THREAD

**Issue by raeesahhy** [WenChentao/3DeeCellTracker#15]
Hi, 

I managed to download 3DeeCellTracker via my Terminal on a 64-bit Ubuntu 20.04.2 LTS, however, the following error was raised in the process. 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.13.1 requires numpy<=1.24.3,>=1.22, but you have numpy 1.19.5 which is incompatible.
```

Despite that, 3DeeCellTracker was downloaded anyway, and I tried to run the 3D_U_net_training-clear notebook but received the following error. 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 6
      4 import warnings
      5 warnings.filterwarnings('ignore')
----> 6 from CellTracker.unet3d import TrainingUNet3D, unet3_a
      7 get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'CellTracker'

```

So I suppose Tensorflow/numpy is still the problem. I would appreciate advice on how to solve it, thanks.

**Comment by WenChentao** [comment]
It seems that the 3DeeCellTracker was not installed in your enviroment due to the dependency conflict between TensorFlow and NumPy. Perhaps you can install an older version of Tensorflow (such as v2.6.0) that is compatible with numpy 1.19.5.

**Comment by raeesahhy** [comment]
Thanks for your quick reply, Wen. 

I tried your suggestion and 3DeeCellTracker was successfully installed. However, when I tried to run the 3D_U_net_training-clear notebook, I received the following error:

```
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

When I tried to run `pip install protobuf==3.2.0`, I received another error: 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.13.0 requires protobuf>=3.19.6, but you have protobuf 3.2.0 which is incompatible.
tensorflow 2.6.0 requires protobuf>=3.9.2, but you have protobuf 3.2.0 which is incompatible.
```

**Comment by WenChentao** [comment]
According to the error information, protobuf==3.2.0 is incompatible with tensorboard 2.13.0, so perhaps you can install protobuf==3.19.6.
If this does not work, you may consider reinstalling all packages in a newly created conda environment.

**Comment by raeesahhy** [comment]
Thanks for your suggestions. 

I tried to install all packages including protobuf==3.19.6 in a fresh conda environment with python 3.8. However, I received this error when I tried to run the same notebook: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 6
      4 import warnings
      5 warnings.filterwarnings('ignore')
----> 6 from CellTracker.unet3d import TrainingUNet3D, unet3_a
      7 get_ipython().run_line_magic('matplotlib', 'inline')

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/CellTracker/unet3d.py:14
     12 import matplotlib.pyplot as plt
     13 import numpy as np
---> 14 from tensorflow.keras.layers import Conv3D, LeakyReLU, Input, MaxPooling3D, UpSampling3D, concatenate, \
     15     BatchNormalization
     16 from tensorflow.keras.models import Model
     17 from tensorflow.keras.preprocessing.image import ImageDataGenerator

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/api/_v2/keras/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.api._v2.keras import __internal__
      4 from keras.api._v2.keras import activations
      5 from keras.api._v2.keras import applications

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras import __internal__
      4 from keras import activations
      5 from keras import applications

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/__internal__/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.__internal__ import backend
      4 from keras.__internal__ import layers
      5 from keras.__internal__ import losses

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/__internal__/backend/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.src.backend import _initialize_variables as initialize_variables
      4 from keras.src.backend import track_variable

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/src/__init__.py:21
      1 # Copyright 2015 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Implementation of the Keras API, the high-level API of TensorFlow.
     16 
     17 Detailed documentation and user guides are available at
     18 [keras.io](https://keras.io).
     19 """
---> 21 from keras.src import applications
     22 from keras.src import distribute
     23 from keras.src import models

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/src/applications/__init__.py:18
      1 # Copyright 2016 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras Applications are premade architectures with pre-trained weights."""
---> 18 from keras.src.applications.convnext import ConvNeXtBase
     19 from keras.src.applications.convnext import ConvNeXtLarge
     20 from keras.src.applications.convnext import ConvNeXtSmall

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/src/applications/convnext.py:28
     25 import numpy as np
     26 import tensorflow.compat.v2 as tf
---> 28 from keras.src import backend
     29 from keras.src import initializers
     30 from keras.src import layers

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/src/backend.py:34
     32 from keras.src import backend_config
     33 from keras.src.distribute import distribute_coordinator_utils as dc
---> 34 from keras.src.dtensor import dtensor_api as dtensor
     35 from keras.src.engine import keras_tensor
     36 from keras.src.utils import control_flow_util

File ~/miniforge3/envs/3dct/lib/python3.8/site-packages/keras/src/dtensor/__init__.py:18
      1 # Copyright 2022 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras' DTensor library."""
---> 18 from tensorflow.compat.v2.experimental import dtensor as dtensor_api

ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (/home/abigail/miniforge3/envs/3dct/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/experimental/__init__.py)
```

**Comment by WenChentao** [comment]
I suppose that you do not need to install protobuf==3.19.6 if you reinstall TensorFlow and other packages in a clean environment.

**Comment by raeesahhy** [comment]
Whoops, I didn't think of that. 

So I tried to install Tensorflow 2.6.0 and 3DeeCellTracker (just those) in an entirely new condo environment with python 3.8. It installed successfully but when I tried to run the notebook, I received this error again: 

```
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

And when I tried to install protobuf==3.2.0, I got this error: 

`ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (/home/abigail/miniforge3/envs/3dct2/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/experimental/__init__.py)`

**Comment by WenChentao** [comment]
I have confirmed that protobuf==3.20.0 works in my Conda environment. You may want to try this version. By the way, I don't understand why you attempted to install protobuf==3.2.0.

**Comment by raeesahhy** [comment]
My apologies, that was a bad typo, I tried 3.20.0 earlier. 

I tried everything again in a fresh conda environment and got another error message: 

`ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (/home/abigail/miniforge3/envs/3dct3/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/experimental/__init__.py)`

I'm a beginner to Python so please forgive my confusion, I'll list the exact steps I took that led to the above message and I hope you can help point out my mistake: 

1. In Terminal: `conda create -n 3dct3 python=3.8 pip`
2. `conda activate 3dct3`
3. `pip install tensorflow==2.6.0`
4. `pip install protobuf==3.20.0`
5. `pip install 3DeeCellTracker==1.0.0`
6. `jupyter notebook`
7. In 3D_U_net_training-clear, 
```
!pip install matplotlib --use-deprecated=legacy-resolver
!pip install tensorflow --use-deprecated=legacy-resolver
```
8. Then: 
```
%load_ext autoreload
%autoreload 2
import os
import warnings
warnings.filterwarnings('ignore')
from CellTracker.unet3d import TrainingUNet3D, unet3_a
%matplotlib inline
```

**Comment by WenChentao** [comment]
Could you list all packages in your environment using the command pip list? 
Also, please attach the complete error message.

**Comment by raeesahhy** [comment]
Thanks for your reply. Here are the packages: 

```
Package                   Version
------------------------- -----------
3DeeCellTracker           1.0.0
absl-py                   0.15.0
asttokens                 2.4.1
astunparse                1.6.3
attrs                     23.2.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bleach                    6.1.0
cachetools                5.3.3
certifi                   2024.2.2
charset-normalizer        3.3.2
clang                     5.0
comm                      0.2.2
contourpy                 1.1.1
csbdeep                   0.8.0
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.0.1
fastjsonschema            2.19.1
flatbuffers               1.12
fonttools                 4.52.4
gast                      0.4.0
google-auth               2.29.0
google-auth-oauthlib      1.0.0
google-pasta              0.2.0
grpcio                    1.64.0
h5py                      3.1.0
idna                      3.7
imageio                   2.34.1
importlib_metadata        7.1.0
importlib_resources       6.4.0
ipykernel                 6.29.4
ipython                   8.12.3
ipython-genutils          0.2.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.2
jupyterlab_pygments       0.3.0
keras                     2.15.0
Keras-Preprocessing       1.1.2
kiwisolver                1.4.5
llvmlite                  0.39.1
Markdown                  3.6
MarkupSafe                2.1.5
matplotlib                3.6.3
matplotlib-inline         0.1.7
mistune                   3.0.2
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.1
notebook                  6.0.0
numba                     0.56.4
numpy                     1.19.5
oauthlib                  3.2.2
opt-einsum                3.3.0
packaging                 24.0
pandocfilters             1.5.1
parso                     0.8.4
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.3.0
pip                       24.0
pkgutil_resolve_name      1.3.10
platformdirs              4.2.2
prometheus_client         0.20.0
prompt_toolkit            3.0.44
protobuf                  3.20.0
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pyasn1                    0.6.0
pyasn1_modules            0.4.0
Pygments                  2.18.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
PyWavelets                1.4.1
pyzmq                     26.0.3
referencing               0.35.1
requests                  2.32.2
requests-oauthlib         2.0.0
rpds-py                   0.18.1
rsa                       4.9
scikit-image              0.19.3
scikit-learn              1.1.2
scipy                     1.10.1
Send2Trash                1.8.3
setuptools                70.0.0
six                       1.15.0
soupsieve                 2.5
stack-data                0.6.3
stardist                  0.8.3
tensorboard               2.14.0
tensorboard-data-server   0.7.2
tensorflow                2.6.0
tensorflow-estimator      2.15.0
termcolor                 1.1.0
terminado                 0.18.1
threadpoolctl             3.5.0
tifffile                  2023.7.10
tinycss2                  1.3.0
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
typing-extensions         3.7.4.3
urllib3                   2.2.1
wcwidth                   0.2.13
webencodings              0.5.1
Werkzeug                  3.0.3
wheel                     0.43.0
wrapt                     1.12.1
zipp                      3.19.0
```

Here's the error message: 

```
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[7], line 6
      4 import warnings
      5 warnings.filterwarnings('ignore')
----> 6 from CellTracker.unet3d import TrainingUNet3D, unet3_a
      7 get_ipython().run_line_magic('matplotlib', 'inline')

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/CellTracker/unet3d.py:14
     12 import matplotlib.pyplot as plt
     13 import numpy as np
---> 14 from tensorflow.keras.layers import Conv3D, LeakyReLU, Input, MaxPooling3D, UpSampling3D, concatenate, \
     15     BatchNormalization
     16 from tensorflow.keras.models import Model
     17 from tensorflow.keras.preprocessing.image import ImageDataGenerator

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/api/_v2/keras/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.api._v2.keras import __internal__
      4 from keras.api._v2.keras import activations
      5 from keras.api._v2.keras import applications

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras import __internal__
      4 from keras import activations
      5 from keras import applications

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/__internal__/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.__internal__ import backend
      4 from keras.__internal__ import layers
      5 from keras.__internal__ import losses

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/__internal__/backend/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.src.backend import _initialize_variables as initialize_variables
      4 from keras.src.backend import track_variable

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/src/__init__.py:21
      1 # Copyright 2015 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Implementation of the Keras API, the high-level API of TensorFlow.
     16 
     17 Detailed documentation and user guides are available at
     18 [keras.io](https://keras.io).
     19 """
---> 21 from keras.src import applications
     22 from keras.src import distribute
     23 from keras.src import models

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/src/applications/__init__.py:18
      1 # Copyright 2016 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras Applications are premade architectures with pre-trained weights."""
---> 18 from keras.src.applications.convnext import ConvNeXtBase
     19 from keras.src.applications.convnext import ConvNeXtLarge
     20 from keras.src.applications.convnext import ConvNeXtSmall

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/src/applications/convnext.py:28
     25 import numpy as np
     26 import tensorflow.compat.v2 as tf
---> 28 from keras.src import backend
     29 from keras.src import initializers
     30 from keras.src import layers

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/src/backend.py:34
     32 from keras.src import backend_config
     33 from keras.src.distribute import distribute_coordinator_utils as dc
---> 34 from keras.src.dtensor import dtensor_api as dtensor
     35 from keras.src.engine import keras_tensor
     36 from keras.src.utils import control_flow_util

File ~/miniforge3/envs/3dct3/lib/python3.8/site-packages/keras/src/dtensor/__init__.py:18
      1 # Copyright 2022 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras' DTensor library."""
---> 18 from tensorflow.compat.v2.experimental import dtensor as dtensor_api

ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (/home/abigail/miniforge3/envs/3dct3/lib/python3.8/site-packages/tensorflow/_api/v2/compat/v2/experimental/__init__.py)
```

**Comment by WenChentao** [comment]
I noticed that keras==2.6.0 is installed in my environment, while keras==2.15.0 is installed in your environment. This version mismatch may be causing the error. You could try running pip install keras==2.6.0.

**Comment by ClaireBookworm** [comment]
Do you think you could share the versions of the various packages you have in the correct working environment (as a sorts of requirements.txt)? This would be super helpful in making sure I have all the compatible versions when setting up the environment at first. Thanks!

**Comment by WenChentao** [comment]
@ClaireBookworm I added a [requirement.txt](https://github.com/WenChentao/3DeeCellTracker/blob/master/requirements.txt) file, which works on my Ubuntu 20.04 system with an NVIDIA GeForce RTX 3080 Ti.

**Comment by ClaireBookworm** [comment]
Thanks so much! What version of python did you use? Seems like some of these only work with 3.8 or 3.9 etc... thanks again!

**Comment by WenChentao** [comment]
@ClaireBookworm I used Python 3.8.13.

**Comment by WenChentao** [comment]
I have confirmed that the compatibility issues between TensorFlow, Keras, and Protobuf are causing these errors. Therefore, users need to specify the correct versions. In my tests, installing TensorFlow 2.6.0, Keras 2.6.0, and Protobuf 3.20.3 resolves these errors. For other TensorFlow versions, users will need to find the appropriate combinations themselves.
